void page_Set_Time(WiFiClient *client)
{
    client->flush();

     String web = "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n";
web +="<style>\n";
web +="body {\n";
web +="font-family: \"Trebuchet MS\", Verdana, sans-serif;\n";
web +="font-size: 16px;\n";
web +="background-color: dimgrey;\n"; 
web +="color: #696969\n;";
web +="padding: 3px;\n";
web +="}\n";

web +="#main {\n";
web +="padding: 5px;\n";
web +="padding-left:  15px;\n";
web +="padding-right: 15px;\n";
web +="background-color: #ffffff;\n";
web +="border-radius: 0 0 5px 5px;\n";
web +="}\n";
web +="h1 {\n";
web +="font-family: Georgia, serif;\n";
web +="border-bottom: 3px solid #cc9900;\n";
web +="color: #996600;\n";
web +="font-size: 30px;\n";
web +="}\n";
web += "</style>\r\n";
            web +="<!DOCTYPE html>\r\n";
            web +="<html>\r\n";
            web +="<script src=\"http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js\"></script>\n";
            web +="<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js\"></script>\n";
            web += "<script>\r\n";
            web += "var ajax = null;\r\n";
            web += "if (window.XMLHttpRequest)\r\n";
            web += "{ajax =new XMLHttpRequest();"; 
            web += "}\r\n";
            web += "else\r\n";
            web += "{ajax=new ActiveXObject(\"Microsoft.XMLHTTP\");}\r\n";
            web += "</script>\r\n";
            web +="<head>\r\n";
            web +="<title>About</title>\n";
            web +="<link href=\"site.css\" rel=\"stylesheet\">\n"; 
         
            web +="</head>";
            web +="<body>\n";
            web +="<div id=\"main\">";
            web +="<h1>Set Time</h1>";
            web +="<h2>\n";
            web +="Time Show";
            web +="<button type=\"button\" onclick= window.location.href=\"/\">Home page</button>\n";
            web +="</h2>\n";
            web += "<p>";
            web +="<canvas id=\"Date\" width=\"250\" height=\"50\"></canvas>\r\n";   // << Add canvas date
            web +="<canvas id=\"Time\" width=\"150\" height=\"50\"></canvas>\r\n";   // << Add canvas time
            web += "</p>\n";
            web +="<p>\n";
            web +="</p>\n";
            web +="<p>\n";
            web +="Set MCU Time\n";
            web +="<input id=\"exit-time\" name=\"mcu_exit-time\" type=\"time\">\n";
            web +="<input id=\"mcu_date\" name=\"mcu_date\" type=\"date\">\n";
            web +="<button type=\"button\" onclick=Click_Settime() >Submit</button>\n";
            web +="</p>\n";
      client->print(web); 
            web ="<p>\n";
            web +="<input id=\"exit-time\" name=\"exit-time_1\" type=\"time\" value=\"00:00\">\n";
            web +="<input type=\"radio\" name=\"Command_1\" value=\"ON\" checked>ON\n";
            web +="<input type=\"radio\" name=\"Command_1\" value=\"OFF\"> OFF\n";
             web +="<input type=\"radio\" name=\"Command_1\" value=\"NOT_USE\"> NOT USE \n";
            web +="<button type=\"button\" onclick=Click_Settime() >SetTime_1</button>\n";
            web +="</p>\n";
            web +="<p>\n";
            web +="<form id=\"myForm\">\n";
            web +="<input id=\"exit-time\" name=\"exit-time_2\" type=\"time\" value=\"00:00\">\n";
            web +="<input type=\"radio\" name=\"Command_2\" value=\"ON\" checked>ON\n";
            web +="<input type=\"radio\" name=\"Command_2\" value=\"OFF\"> OFF\n";
            web +="<input type=\"radio\" name=\"Command_2\" value=\"NOT_USE\"> NOT USE \n";
            web +="<button type=\"button\" onclick=Click_Settime() >SetTime_2</button>\n";
            web +="</form>\n";
            web +="</p>\n";
            web +="<p>\n";
            web +="<input id=\"exit-time\" name=\"exit-time_3\" type=\"time\" value=\"00:00\">\n";
            web +="<input type=\"radio\" name=\"Command_3\" value=\"ON\" checked>ON\n";
            web +="<input type=\"radio\" name=\"Command_3\" value=\"OFF\"> OFF\n";
            web +="<input type=\"radio\" name=\"Command_3\" value=\"NOT USE\"> NOT USE \n";
            web +="<button type=\"button\" onclick=Click_Settime() >SetTime_3</button>\n";
            web +="</p>\n";
            web +="<p>\n";
            web +="<input id=\"exit-time\" name=\"exit-time_4\" type=\"time\" value=\"00:00\">\n";
            web +="<input type=\"radio\" name=\"Command_4\" value=\"ON\" checked> ON\n";
            web +="<input type=\"radio\" name=\"Command_4\" value=\"OFF\"> OFF\n";
            web +="<input type=\"radio\" name=\"Command_4\" value=\"NOT_USE\"> NOT USE \n";
            web +="<button type=\"button\" onclick=Click_Settime() >SetTime_4</button>\n";
            web +="</p>\n";
            web +="</div>";
            web +="</body>\n";

    client->print(web);
            web = "<script>\r\n";

            web += "function draw_Time_CLock(ctx,w,h,Hr,min,sec)\r\n";
            web += "{\r\n";
            web += "ctx.save();\n";   
            web += "ctx.beginPath();\n";
         //   web += "ctx.translate(w, h);\n"; 
            web += "ctx.clearRect(0, 0, w, h);\n";
            web += "ctx.font=\"20px Comic Sans MS\";\n";
            web += "ctx.fillStyle = \"black\";\n";
            web += "ctx.textAlign = \"center\";\n";
            web += "var massage_Time = Hr+\" : \"+min+\" : \"+sec;\n";
            web += "ctx.fillText(massage_Time,w/2,h/2);\n";
            web +="ctx.restore();\n";
            web += "}\r\n";
            
            web += "function draw_Date(ctx,w,h,day_of_week,day,mounth,year)\r\n";
            web += "{\r\n";
            web += "ctx.save();\n";   
            web += "ctx.beginPath();\n";
         //   web += "ctx.translate(w, h);\n"; 
            web += "ctx.clearRect(0, 0, w, h);\n";
            web += "ctx.font=\"20px Comic Sans MS\";\n";
            web += "ctx.fillStyle = \"black\";\n";
            web += "ctx.textAlign = \"center\";\n";
            web += "var massage_date = day_of_week+\"  \"+day+\"/\"+mounth+\"/\"+year;\n";
            web += "ctx.fillText(massage_date,w/2,h/2);\n";
            web +="ctx.restore();\n";
            web += "}\r\n";
            
            web += "function Click_Settime(Hr,Min,Sec,Day_of_week,day,mounth,year)\r\n";
            web +="{\r\n";
            web +="";
        //    web +="ajaxLoad(\"GET\",Time+\'.html\',null,null);"
            web += "}\r\n";
            web += "function SetFunction_Time(Menu,Status,Hr,Min,Sec,Day_of_week)\r\n";
            web +="{\r\n";
            web +="";
        //    web +="ajaxLoad(\"GET\",Time+\'.html\',null,null);"
            web += "}\r\n";
            //////////////////Data //////////////////
            web +="function Set_Initial()\n";
            web +="{\n";
            web +="var Flag_Initial = 0;\n";
            web +="document.getElementsByName(\"mcu_exit-time\")[0].value = getUser_Time();\n";
            web +="document.getElementsByName(\"mcu_date\")[0].value = getUser_Date();\n";
            web +="}\n";
            web +="function Initial_Page()\n";
            web +="{\n";
            web +="\n";
            web +="if(Flag_Initial == 0)\n";
            web +="{\n";
            web +="}else{\n";
            web +="}\n";
            web +="}\n";
            //////// Get Time Date On computer user ///// 
            web +="function checkTime(i) {\n";
            web +="if (i.toString().length == 1) {i = \"0\" + i}\n"; // add zero in front of numbers < 10
            web +="return i;\n";
            web +="}\n";

            web +="function getUser_Date(){\n";
            web +="var now = new Date();\n";
            web +="var day = (\"0\" + now.getDate()).slice(-2);\n";
            web +="var month = (\"0\" + (now.getMonth() + 1)).slice(-2);\n";
            web +="var today = now.getFullYear()+\"-\"+(month)+\"-\"+(day);\n";
            web +="return today;\n";
            web +="}\n";
            web +="function getUser_Time(){\n";
            web +="var now     = new Date();\n"; 
            web +="var user_time = checkTime(now.getHours())+\":\"+checkTime(now.getMinutes())+\":\"+checkTime(now.getSeconds());\n";
            web +="return user_time;\n";
            web +="}\n";
            web +="function getDateTime() {\n";
            web +="var now     = new Date();\n"; 
            web +="var year    = now.getFullYear();\n";
            web +="var month   = now.getMonth()+1;\n"; 
            web +="var day     = now.getDate();\n";
            web +="var hour    = now.getHours();\n";
            web +="var minute  = now.getMinutes();\n";
            web +="var second  = now.getSeconds();\n"; 
            web +="if(month.toString().length == 1) {\n";
            web +="var month = '0'+month;\n";
            web +="}\n";
            web +="if(day.toString().length == 1) {\n";
            web +="var day = '0'+day;\n";
            web +="}\n";   
            web +="if(hour.toString().length == 1) {\n";
            web +="var hour = '0'+hour;\n";
            web +="}\n";
            web +="if(minute.toString().length == 1) {\n";
            web +="var minute = '0'+minute;\n";
            web +="}\n";
            web +="if(second.toString().length == 1) {\n";
            web +="var second = '0'+second;\n";
            web +="}\n";  
            web +="var dateTime = year+'/'+month+'/'+day+' '+hour+':'+minute+':'+second;\n";   
            web +="return dateTime;\n";
            web +="}\n";
            web += "</script>\r\n";
           client->print(web);  
            web ="<script>\n";
            web +="var canvase_date = document.getElementById('Date');\n";      // Draw date
            web +="var canvase_date_context = canvase_date.getContext('2d');\n";
            web +="draw_Date(canvase_date_context,canvase_date.width,canvase_date.height,\"----\",\"-\",\"-\",\"-\");\r\n";
            
            web +="var canvase_Time = document.getElementById('Time');\n";      // Draw Time
            web +="var canvase_Time_context = canvase_Time.getContext('2d');\n";
            web +="draw_Time_CLock(canvase_Time_context,canvase_Time.width,canvase_Time.height,\"-\",\"-\",\"-\");\r\n";
            web +="</script>\n";
            web +="<script>\n";
            web += "function update_temp_humi()\r\n"; 
            web += "{\r\n";
            web += "var URL_T = \"/Temp_.html\";\r\n";
            web += "ajaxLoad(\"GET\",URL_T,\'temp_humi\',null);\r\n";
            web += "}\r\n";
            web += "</script>\r\n";
            ////////////////////////////////////////////////////////////////////////
            web += "<script type=\"text/javascript\">\n";
            web += "$('#myForm input').on('change', function() {\n";
            web += "alert($('input[name=Command_2]:checked', '#myForm').val());\n";
            web += "alert($('input[name=exit-time]:checked', '#myForm').val());\n"; 
            web +="});\n";
            web +="</script>\n";
            //////////////////////////// Interupt Call Update Data Time ///////////////
            web +="<script>\n";
            web +="Set_Initial();\n";
            web += "setInterval(\"update_temp_humi()\",1000);\r\n";
            web +="</script>\n";
            client->print(web);
            web ="<script>\n";
            web += "function ajaxLoad(method ,URL,displayElementId,sendData)\r\n";
            web += "{\r\n";
            web += "if(!ajax){alert(\"not support\");return;}\r\n";
            web += "ajax.open(method,URL,true);\r\n";
            web += "ajax.onreadystatechange = function()\r\n";
            web += "{\r\n";
            web += "if(ajax.readyState == 4 && ajax.status==200)\r\n";
            web += "{\r\n";
            web += "var ajax_result = ajax.responseText;\r\n";
            web += "var el = document.getElementById(displayElementId);\r\n";
            web += "var data_all = ajax.responseText.split(\":\");\n";
            web += "var data_temp = data_all[0];\n";
            web += "var data_Hum  = data_all[1];\n";
            web += "var data_LED_1 = data_all[2];\n";
            web += "var data_LED_2 = data_all[3];\n";
            web += "var Hr         = data_all[4];\n";
            web += "var min        = data_all[5];\n";
            web += "var sec        = data_all[6];\n";
            web += "var day_of_week= data_all[7];\n";
            web += "var day        = data_all[8];\n";
            web += "var mounth      = data_all[9];\n";
            web += "var year       = data_all[10];\n";
        //  web +="var canvase_temp_hum = document.getElementById('Temp_Hum');\n";
        //  web +="var canvase_temp_hum_context = canvase_temp_hum.getContext('2d');\n";
        //    web +="draw_Temp_Hum(canvase_temp_hum_context,canvase_temp_hum.width,canvase_temp_hum.height,\"Temp \"+data_temp+ \" C\",\"Hum \"+data_Hum+\" %RH\");\n";
            web +="draw_Date(canvase_date_context,canvase_date.width,canvase_date.height,day_of_week,day,mounth,year);\r\n";
            web +="draw_Time_CLock(canvase_Time_context,canvase_Time.width,canvase_Time.height,Hr,min,sec);\r\n";
        //   web +="var canvas = document.getElementById('Led_Canvas');\n";
        //   web +="var context = canvas.getContext('2d');\n";
        //    web +="draw_LAMP(context,centerX/2 ,centerY ,80,data_LED_1);\n";
        //    web +="draw_LAMP(context,centerX*3/2,centerY,80,data_LED_2);\n";
        
            web += "}\r\n";
            web += "}\r\n";	
            web += "ajax.send(sendData);\r\n";
            web += "}\r\n";
             web += "</script>\r\n";
            web +="</html>";
        client->print(web);
}

